volumes:
  prometheus_data:
  grafana_data:

services:

  speedtest:
    build:
      context: ./speedtest
    container_name: speedtest
    restart: unless-stopped
    ports:
      - "9104:9104"
    mem_limit: 128m

  prometheus:
    image: prom/prometheus:v2.49.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=72h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    ports:
      - "9090:9090"
    mem_limit: 768m

  nodeexporter:
    image: prom/node-exporter:v1.8.1
    container_name: nodeexporter
    pid: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    restart: unless-stopped
    ports:
      - "9100:9100"
    mem_limit: 64m

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    restart: unless-stopped
    ports:
      - "8080:8080"
    mem_limit: 256m
    command:
      - --docker_only=true

  grafana:
    image: grafana/grafana:10.2.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    restart: unless-stopped
    ports:
      - "3000:3000"
    mem_limit: 512m
